In [2]:
import pandas as pd
import numpy as np
import json
from docx import Document
import os

In [2]:
def extract_text_from_docx(docx_path):
    """Extract all text from a Word document."""
    doc = Document(docx_path)
    full_text = [para.text for para in doc.paragraphs]
    return '\n'.join(full_text)

def text_to_json(text):
    """Convert text to JSON format, assuming the text is valid JSON."""
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return None

In [3]:
directory_path = r"C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data"
output_file_path = r"C:\Users\fatim\OneDrive\Desktop\semester 7\deep\assignment 1\aggregated.json"

In [4]:
all_json_data = []

for i in range(1, 73):
    if i == 38:
        continue  # Skip this iteration
    
    docx_path = os.path.join(directory_path, f'{i}.docx')
    
    if not os.path.isfile(docx_path):
        print(f"File not found: {docx_path}")
        continue  # Skip to the next iteration if the file does not exist

    print(f"Processing: {docx_path}")

    try:
        # Extract text from the Word document
        text = extract_text_from_docx(docx_path)

        # Convert extracted text to JSON
        json_data = text_to_json(text)

        # Check if JSON data was successfully created
        if json_data is not None:
            all_json_data.append(json_data)  # Append the JSON data to the list
        else:
            print(f"Failed to convert text to JSON for {docx_path}.")
    except Exception as e:
        print(f"An error occurred while processing {docx_path}: {e}")

# Write all JSON data to a single JSON file
with open(output_file_path, 'w') as f:
    json.dump(all_json_data, f, indent=4)

print(f"All data has been written to {output_file_path}.")

Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\1.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\2.docx

Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\3.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\4.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\5.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\6.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\7.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\8.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\9.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\10.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\11.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\12.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\13.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\14.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\15.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\16.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\17.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\18.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\19.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\20.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\21.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\22.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\23.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\24.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\25.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\26.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\27.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\28.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\29.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\30.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\31.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\32.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\33.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\34.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\35.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\36.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\37.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\39.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\40.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\41.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\42.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\43.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\44.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\45.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\46.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\47.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\48.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\49.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\50.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\51.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\52.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\53.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\54.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\55.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\56.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\57.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\58.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\59.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\60.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\61.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\62.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\63.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\64.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\65.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\66.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\67.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\68.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\69.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\70.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\71.docx
Processing: C:\Users\fatim\OneDrive\Desktop\semester 7\deep\Flights Data\Flights Data\72.docx
All data has been written to C:\Users\fatim\OneDrive\Desktop\semester 7\deep\assignment 1\aggregated.json.

In [3]:
json_file_path = r"C:\Users\fatim\OneDrive\Desktop\semester 7\deep\assignment 1\aggregated.json"

if not os.path.isfile(json_file_path):
    print(f"File not found: {json_file_path}")
else:
    try:
        # Read JSON data from the file
        with open(json_file_path, 'r') as file:
            data = json.load(file)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

In [4]:
df_list = []

# Loop over each JSON object
for json_obj in data:
    # Normalize the JSON data
    df = pd.DataFrame(json_obj)
    # Append the resulting DataFrame to the list
    df_list.append(df)

# Concatenate all DataFrames into one
df = pd.concat(df_list, ignore_index=True)

df

,type,status,departure,arrival,airline,flight,codeshared
0,departure,active,"{'iataCode': 'lhe', 'icaoCode': 'opla', 'termi...","{'iataCode': 'ist', 'icaoCode': 'ltfm', 'sched...","{'name': 'pakistan international airlines', 'i...","{'number': '5715', 'iataNumber': 'pk5715', 'ic...","{'airline': {'name': 'turkish airlines', 'iata..."
1,departure,active,"{'iataCode': 'lhe', 'icaoCode': 'opla', 'termi...","{'iataCode': 'ist', 'icaoCode': 'ltfm', 'sched...","{'name': 'turkish airlines', 'iataCode': 'tk',...","{'number': '715', 'iataNumber': 'tk715', 'icao...",NaN
2,departure,active,"{'iataCode': 'lhe', 'icaoCode': 'opla', 'termi...","{'iataCode': 'jed', 'icaoCode': 'oejn', 'termi...","{'name': 'pakistan international airlines', 'i...","{'number': '859', 'iataNumber': 'pk859', 'icao...",NaN
3,departure,active,"{'iataCode': 'lhe', 'icaoCode': 'opla', 'termi...","{'iataCode': 'cmb', 'icaoCode': 'vcbi', 'sched...","{'name': 'malaysia airlines', 'iataCode': 'mh'...","{'number': '9032', 'iataNumber': 'mh9032', 'ic...","{'airline': {'name': 'srilankan airlines', 'ia..."
4,departure,active,"{'iataCode': 'lhe', 'icaoCode': 'opla', 'termi...","{'iataCode': 'cmb', 'icaoCode': 'vcbi', 'sched...","{'name': 'srilankan airlines', 'iataCode': 'ul...","{'number': '154', 'iataNumber': 'ul154', 'icao...",NaN
...,...,...,...,...,...,...,...
81387,departure,active,"{'iataCode': 'isb', 'icaoCode': 'opis', 'delay...","{'iataCode': 'doh', 'icaoCode': 'othh', 'bagga...","{'name': 'qatar airways', 'iataCode': 'qr', 'i...","{'number': '633', 'iataNumber': 'qr633', 'icao...",NaN
81388,departure,active,"{'iataCode': 'isb', 'icaoCode': 'opis', 'delay...","{'iataCode': 'ruh', 'icaoCode': 'oerk', 'termi...","{'name': 'flynas', 'iataCode': 'xy', 'icaoCode...","{'number': '316', 'iataNumber': 'xy316', 'icao...",NaN
81389,departure,active,"{'iataCode': 'isb', 'icaoCode': 'opis', 'delay...","{'iataCode': 'kwi', 'icaoCode': 'okkk', 'termi...","{'name': 'kuwait airways', 'iataCode': 'ku', '...","{'number': '206', 'iataNumber': 'ku206', 'icao...",NaN
81390,departure,active,"{'iataCode': 'isb', 'icaoCode': 'opis', 'gate'...","{'iataCode': 'auh', 'icaoCode': 'omaa', 'termi...","{'name': 'klm', 'iataCode': 'kl', 'icaoCode': ...","{'number': '3930', 'iataNumber': 'kl3930', 'ic...","{'airline': {'name': 'etihad airways', 'iataCo..."
81391,departure,active,"{'iataCode': 'isb', 'icaoCode': 'opis', 'gate'...","{'iataCode': 'auh', 'icaoCode': 'omaa', 'termi...","{'name': 'etihad airways', 'iataCode': 'ey', '...","{'number': '232', 'iataNumber': 'ey232', 'icao...",NaN

In [5]:
df['departure_iata'] = df['departure'].apply(lambda x: x.get('iataCode'))
df['departure_icao'] = df['departure'].apply(lambda x: x.get('icaoCode'))
df['departure_terminal'] = df['departure'].apply(lambda x: x.get('terminal'))
df['departure_delay'] = df['departure'].apply(lambda x: x.get('delay'))
df['departure_scheduledTime'] = df['departure'].apply(lambda x: x.get('scheduledTime'))
df['departure_estimatedTime'] = df['departure'].apply(lambda x: x.get('estimatedTime'))

In [6]:
df['arrival_iata'] = df['arrival'].apply(lambda x: x.get('iataCode'))
df['arrival_icao'] = df['arrival'].apply(lambda x: x.get('icaoCode'))
df['arrival_scheduledTime'] = df['arrival'].apply(lambda x: x.get('scheduledTime'))

In [7]:
df['airline_name'] = df['airline'].apply(lambda x: x.get('name'))
df['airline_iata'] = df['airline'].apply(lambda x: x.get('iataCode'))
df['airline_icao'] = df['airline'].apply(lambda x: x.get('icaoCode'))

df['flight_number'] = df['flight'].apply(lambda x: x.get('number'))
df['flight_iataNumber'] = df['flight'].apply(lambda x: x.get('iataNumber'))
df['flight_icaoNumber'] = df['flight'].apply(lambda x: x.get('icaoNumber'))

In [8]:
df['codeshared_airline'] = df['codeshared'].apply(lambda x: x['airline'].get('name') if pd.notna(x) else np.nan)
df['codeshared_iata'] = df['codeshared'].apply(lambda x: x['airline'].get('iataCode') if pd.notna(x) else np.nan)
df['codeshared_flight_number'] = df['codeshared'].apply(lambda x: x['flight'].get('number') if pd.notna(x) else np.nan)

In [9]:
df = df.drop(['departure', 'arrival', 'airline', 'flight', 'codeshared'], axis=1)

In [10]:
df

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,arrival_scheduledTime,airline_name,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number
0,departure,active,lhe,opla,m,10.0,2023-07-13t06:00:00.000,2023-07-13t06:10:00.000,ist,ltfm,2023-07-13t10:45:00.000,pakistan international airlines,pk,pia,5715,pk5715,pia5715,turkish airlines,tk,715
1,departure,active,lhe,opla,m,10.0,2023-07-13t06:00:00.000,2023-07-13t06:10:00.000,ist,ltfm,2023-07-13t10:45:00.000,turkish airlines,tk,thy,715,tk715,thy715,NaN,NaN,NaN
2,departure,active,lhe,opla,m,20.0,2023-07-13t06:50:00.000,2023-07-13t07:10:00.000,jed,oejn,2023-07-13t10:10:00.000,pakistan international airlines,pk,pia,859,pk859,pia859,NaN,NaN,NaN
3,departure,active,lhe,opla,m,NaN,2023-07-13t07:05:00.000,2023-07-13t07:05:00.000,cmb,vcbi,2023-07-13t11:30:00.000,malaysia airlines,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,154
4,departure,active,lhe,opla,m,NaN,2023-07-13t07:05:00.000,2023-07-13t07:05:00.000,cmb,vcbi,2023-07-13t11:30:00.000,srilankan airlines,ul,alk,154,ul154,alk154,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81387,departure,active,isb,opis,None,17.0,2024-07-10t03:35:00.000,2024-07-10t03:35:00.000,doh,othh,2024-07-10t05:15:00.000,qatar airways,qr,qtr,633,qr633,qtr633,NaN,NaN,NaN
81388,departure,active,isb,opis,None,23.0,2024-07-10t04:15:00.000,2024-07-10t04:30:00.000,ruh,oerk,2024-07-10t06:30:00.000,flynas,xy,kne,316,xy316,kne316,NaN,NaN,NaN
81389,departure,active,isb,opis,None,4.0,2024-07-10t04:25:00.000,2024-07-10t04:35:00.000,kwi,okkk,2024-07-10t06:25:00.000,kuwait airways,ku,kac,206,ku206,kac206,NaN,NaN,NaN
81390,departure,active,isb,opis,None,37.0,2024-07-10t04:35:00.000,2024-07-10t05:12:00.000,auh,omaa,2024-07-10t07:00:00.000,klm,kl,klm,3930,kl3930,klm3930,etihad airways,ey,232
81391,departure,active,isb,opis,None,37.0,2024-07-10t04:35:00.000,2024-07-10t05:12:00.000,auh,omaa,2024-07-10t07:00:00.000,etihad airways,ey,etd,232,ey232,etd232,NaN,NaN,NaN

In [11]:
df['codeshared_airline'].fillna('No Codeshare', inplace=True)

C:\Users\fatim\AppData\Local\Temp\ipykernel_13960\3398328479.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['codeshared_airline'].fillna('No Codeshare', inplace=True)

In [12]:
df

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,arrival_scheduledTime,airline_name,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number
0,departure,active,lhe,opla,m,10.0,2023-07-13t06:00:00.000,2023-07-13t06:10:00.000,ist,ltfm,2023-07-13t10:45:00.000,pakistan international airlines,pk,pia,5715,pk5715,pia5715,turkish airlines,tk,715
1,departure,active,lhe,opla,m,10.0,2023-07-13t06:00:00.000,2023-07-13t06:10:00.000,ist,ltfm,2023-07-13t10:45:00.000,turkish airlines,tk,thy,715,tk715,thy715,No Codeshare,NaN,NaN
2,departure,active,lhe,opla,m,20.0,2023-07-13t06:50:00.000,2023-07-13t07:10:00.000,jed,oejn,2023-07-13t10:10:00.000,pakistan international airlines,pk,pia,859,pk859,pia859,No Codeshare,NaN,NaN
3,departure,active,lhe,opla,m,NaN,2023-07-13t07:05:00.000,2023-07-13t07:05:00.000,cmb,vcbi,2023-07-13t11:30:00.000,malaysia airlines,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,154
4,departure,active,lhe,opla,m,NaN,2023-07-13t07:05:00.000,2023-07-13t07:05:00.000,cmb,vcbi,2023-07-13t11:30:00.000,srilankan airlines,ul,alk,154,ul154,alk154,No Codeshare,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81387,departure,active,isb,opis,None,17.0,2024-07-10t03:35:00.000,2024-07-10t03:35:00.000,doh,othh,2024-07-10t05:15:00.000,qatar airways,qr,qtr,633,qr633,qtr633,No Codeshare,NaN,NaN
81388,departure,active,isb,opis,None,23.0,2024-07-10t04:15:00.000,2024-07-10t04:30:00.000,ruh,oerk,2024-07-10t06:30:00.000,flynas,xy,kne,316,xy316,kne316,No Codeshare,NaN,NaN
81389,departure,active,isb,opis,None,4.0,2024-07-10t04:25:00.000,2024-07-10t04:35:00.000,kwi,okkk,2024-07-10t06:25:00.000,kuwait airways,ku,kac,206,ku206,kac206,No Codeshare,NaN,NaN
81390,departure,active,isb,opis,None,37.0,2024-07-10t04:35:00.000,2024-07-10t05:12:00.000,auh,omaa,2024-07-10t07:00:00.000,klm,kl,klm,3930,kl3930,klm3930,etihad airways,ey,232
81391,departure,active,isb,opis,None,37.0,2024-07-10t04:35:00.000,2024-07-10t05:12:00.000,auh,omaa,2024-07-10t07:00:00.000,etihad airways,ey,etd,232,ey232,etd232,No Codeshare,NaN,NaN

In [13]:
df['departure_scheduledTime'] = pd.to_datetime(df['departure_scheduledTime'])
df['departure_estimatedTime'] = pd.to_datetime(df['departure_estimatedTime'])
df['arrival_scheduledTime'] = pd.to_datetime(df['arrival_scheduledTime'])

In [14]:
df['departure_delay'].fillna(df['departure_delay'].mean(), inplace=True)
df['delay_time'] = (df['departure_estimatedTime'] - df['departure_scheduledTime']).dt.total_seconds() / 60

C:\Users\fatim\AppData\Local\Temp\ipykernel_13960\2372180787.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['departure_delay'].fillna(df['departure_delay'].mean(), inplace=True)

In [15]:
df

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,...,airline_name,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number,delay_time
0,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,pakistan international airlines,pk,pia,5715,pk5715,pia5715,turkish airlines,tk,715,10.0
1,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,turkish airlines,tk,thy,715,tk715,thy715,No Codeshare,NaN,NaN,10.0
2,departure,active,lhe,opla,m,20.000000,2023-07-13 06:50:00,2023-07-13 07:10:00,jed,oejn,...,pakistan international airlines,pk,pia,859,pk859,pia859,No Codeshare,NaN,NaN,20.0
3,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,malaysia airlines,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,154,0.0
4,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,srilankan airlines,ul,alk,154,ul154,alk154,No Codeshare,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81387,departure,active,isb,opis,None,17.000000,2024-07-10 03:35:00,2024-07-10 03:35:00,doh,othh,...,qatar airways,qr,qtr,633,qr633,qtr633,No Codeshare,NaN,NaN,0.0
81388,departure,active,isb,opis,None,23.000000,2024-07-10 04:15:00,2024-07-10 04:30:00,ruh,oerk,...,flynas,xy,kne,316,xy316,kne316,No Codeshare,NaN,NaN,15.0
81389,departure,active,isb,opis,None,4.000000,2024-07-10 04:25:00,2024-07-10 04:35:00,kwi,okkk,...,kuwait airways,ku,kac,206,ku206,kac206,No Codeshare,NaN,NaN,10.0
81390,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,klm,kl,klm,3930,kl3930,klm3930,etihad airways,ey,232,37.0
81391,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,etihad airways,ey,etd,232,ey232,etd232,No Codeshare,NaN,NaN,37.0

In [16]:
df_active = df[df['status'] == 'active'].copy()

In [17]:
df_active

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,...,airline_name,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number,delay_time
0,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,pakistan international airlines,pk,pia,5715,pk5715,pia5715,turkish airlines,tk,715,10.0
1,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,turkish airlines,tk,thy,715,tk715,thy715,No Codeshare,NaN,NaN,10.0
2,departure,active,lhe,opla,m,20.000000,2023-07-13 06:50:00,2023-07-13 07:10:00,jed,oejn,...,pakistan international airlines,pk,pia,859,pk859,pia859,No Codeshare,NaN,NaN,20.0
3,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,malaysia airlines,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,154,0.0
4,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,srilankan airlines,ul,alk,154,ul154,alk154,No Codeshare,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81387,departure,active,isb,opis,None,17.000000,2024-07-10 03:35:00,2024-07-10 03:35:00,doh,othh,...,qatar airways,qr,qtr,633,qr633,qtr633,No Codeshare,NaN,NaN,0.0
81388,departure,active,isb,opis,None,23.000000,2024-07-10 04:15:00,2024-07-10 04:30:00,ruh,oerk,...,flynas,xy,kne,316,xy316,kne316,No Codeshare,NaN,NaN,15.0
81389,departure,active,isb,opis,None,4.000000,2024-07-10 04:25:00,2024-07-10 04:35:00,kwi,okkk,...,kuwait airways,ku,kac,206,ku206,kac206,No Codeshare,NaN,NaN,10.0
81390,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,klm,kl,klm,3930,kl3930,klm3930,etihad airways,ey,232,37.0
81391,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,etihad airways,ey,etd,232,ey232,etd232,No Codeshare,NaN,NaN,37.0

In [18]:
df_active

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,...,airline_name,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number,delay_time
0,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,pakistan international airlines,pk,pia,5715,pk5715,pia5715,turkish airlines,tk,715,10.0
1,departure,active,lhe,opla,m,10.000000,2023-07-13 06:00:00,2023-07-13 06:10:00,ist,ltfm,...,turkish airlines,tk,thy,715,tk715,thy715,No Codeshare,NaN,NaN,10.0
2,departure,active,lhe,opla,m,20.000000,2023-07-13 06:50:00,2023-07-13 07:10:00,jed,oejn,...,pakistan international airlines,pk,pia,859,pk859,pia859,No Codeshare,NaN,NaN,20.0
3,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,malaysia airlines,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,154,0.0
4,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,srilankan airlines,ul,alk,154,ul154,alk154,No Codeshare,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81387,departure,active,isb,opis,None,17.000000,2024-07-10 03:35:00,2024-07-10 03:35:00,doh,othh,...,qatar airways,qr,qtr,633,qr633,qtr633,No Codeshare,NaN,NaN,0.0
81388,departure,active,isb,opis,None,23.000000,2024-07-10 04:15:00,2024-07-10 04:30:00,ruh,oerk,...,flynas,xy,kne,316,xy316,kne316,No Codeshare,NaN,NaN,15.0
81389,departure,active,isb,opis,None,4.000000,2024-07-10 04:25:00,2024-07-10 04:35:00,kwi,okkk,...,kuwait airways,ku,kac,206,ku206,kac206,No Codeshare,NaN,NaN,10.0
81390,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,klm,kl,klm,3930,kl3930,klm3930,etihad airways,ey,232,37.0
81391,departure,active,isb,opis,None,37.000000,2024-07-10 04:35:00,2024-07-10 05:12:00,auh,omaa,...,etihad airways,ey,etd,232,ey232,etd232,No Codeshare,NaN,NaN,37.0

In [19]:
bin_edges = [-np.inf, 30, 60, 120, 240, 480, 720, 1440, np.inf]  # Adjusted to include 0 delay

# Bin the delay times into 8 categories
df_active['delay_time_bin'] = pd.cut(df['delay_time'], bins=bin_edges, labels=False)

# Step 4: Handle NaN values (for 0 delay_time)
# Assign 0 (first bin) to NaN values, since 0-minute delays should fall into the first bin
df_active['delay_time_bin'].fillna(0, inplace=True)

# Step 5: Verify the results
print(df_active[['departure_scheduledTime', 'departure_estimatedTime', 'delay_time', 'delay_time_bin']].head())

  departure_scheduledTime departure_estimatedTime  delay_time  delay_time_bin
0     2023-07-13 06:00:00     2023-07-13 06:10:00        10.0             0.0
1     2023-07-13 06:00:00     2023-07-13 06:10:00        10.0             0.0
2     2023-07-13 06:50:00     2023-07-13 07:10:00        20.0             0.0
3     2023-07-13 07:05:00     2023-07-13 07:05:00         0.0             0.0
4     2023-07-13 07:05:00     2023-07-13 07:05:00         0.0             0.0

C:\Users\fatim\AppData\Local\Temp\ipykernel_13960\852408451.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_active['delay_time_bin'].fillna(0, inplace=True)

In [20]:
# Print the bin counts to check how many data points are in each bin
bin_counts = df_active['delay_time_bin'].value_counts().sort_index()
print(bin_counts)

delay_time_bin
0.0    68699
1.0     2693
2.0     1892
3.0     1478
4.0      802
5.0      243
6.0       89
7.0        1
Name: count, dtype: int64

In [21]:
df_active['departure_hour'] = df_active['departure_scheduledTime'].dt.hour
df_active['departure_day'] = df_active['departure_scheduledTime'].dt.day
df_active['arrival_hour'] = df_active['arrival_scheduledTime'].dt.hour
df_active['arrival_day'] = df_active['arrival_scheduledTime'].dt.day

In [22]:
# resampling as the data is highly skewed
from sklearn.utils import resample
df_majority = df_active[df_active['delay_time'] == 0]
df_minority = df_active[df_active['delay_time'] != 0]

In [23]:
df_minority_upsampled = resample(df_minority, 
                                 replace=True,  # Sample with replacement
                                 n_samples=len(df_majority),  # Match number of majority samples
                                 random_state=42)  # Set seed for reproducibility

In [24]:
df_balanced = pd.concat([df_majority, df_minority_upsampled])

In [25]:
df_balanced

,type,status,departure_iata,departure_icao,departure_terminal,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_iata,arrival_icao,...,flight_icaoNumber,codeshared_airline,codeshared_iata,codeshared_flight_number,delay_time,delay_time_bin,departure_hour,departure_day,arrival_hour,arrival_day
3,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,mas9032,srilankan airlines,ul,154,0.0,0.0,7,13,11,13
4,departure,active,lhe,opla,m,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,cmb,vcbi,...,alk154,No Codeshare,NaN,NaN,0.0,0.0,7,13,11,13
6,departure,active,lhe,opla,m,34.134127,2023-07-13 08:00:00,2023-07-13 08:00:00,kdu,opsd,...,pia6453,No Codeshare,NaN,NaN,0.0,0.0,8,13,9,13
7,departure,active,lhe,opla,m,10.000000,2023-07-13 09:00:00,2023-07-13 09:00:00,khi,opkc,...,abq401,No Codeshare,NaN,NaN,0.0,0.0,9,13,10,13
8,departure,active,lhe,opla,m,34.134127,2023-07-13 09:25:00,2023-07-13 09:25:00,doh,othh,...,ibe7915,qatar airways,qr,629,0.0,0.0,9,13,11,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7434,departure,active,lhe,opla,m,34.134127,2023-11-01 08:35:00,NaT,doh,othh,...,jbu5586,qatar airways,qr,629,NaN,0.0,8,1,10,1
43256,departure,active,khi,opkc,m,18.000000,2024-02-25 13:15:00,2024-02-25 13:25:00,jed,oejn,...,kne638,No Codeshare,NaN,NaN,10.0,0.0,13,25,16,25
32969,departure,active,khi,opkc,m,2.000000,2023-10-17 17:50:00,2023-10-17 17:41:00,cmb,vcbi,...,alk184,No Codeshare,NaN,NaN,-9.0,0.0,17,17,22,17
70669,departure,active,isb,opis,None,10.000000,2024-02-07 03:10:00,2024-02-07 03:20:00,doh,othh,...,rwd1572,qatar airways,qr,633,10.0,0.0,3,7,5,7
9019,departure,active,lhe,opla,main,40.000000,2023-11-26 03:20:00,2023-11-26 04:00:00,dxb,omdb,...,aca7617,emirates,ek,623,40.0,1.0,3,26,5,26

In [26]:
bin_counts = df_balanced['delay_time_bin'].value_counts().sort_index()
print(bin_counts)

delay_time_bin
0.0    81973
1.0     4401
2.0     3047
3.0     2404
4.0     1254
5.0      369
6.0      156
Name: count, dtype: int64

In [27]:
df_balanced.columns

Index(['type', 'status', 'departure_iata', 'departure_icao',
       'departure_terminal', 'departure_delay', 'departure_scheduledTime',
       'departure_estimatedTime', 'arrival_iata', 'arrival_icao',
       'arrival_scheduledTime', 'airline_name', 'airline_iata', 'airline_icao',
       'flight_number', 'flight_iataNumber', 'flight_icaoNumber',
       'codeshared_airline', 'codeshared_iata', 'codeshared_flight_number',
       'delay_time', 'delay_time_bin', 'departure_hour', 'departure_day',
       'arrival_hour', 'arrival_day'],
      dtype='object')

In [109]:
# categorical_cols = [
#     'arrival_iata', 'arrival_icao', 
#     'airline_name', 'departure_iata', 
#     'departure_icao', 'departure_terminal'
# ]

# # Apply one-hot encoding
# df_encoded = pd.get_dummies(df_balanced, columns=categorical_cols, drop_first=True)

# df_encoded

,type,status,departure_delay,departure_scheduledTime,departure_estimatedTime,arrival_scheduledTime,airline_iata,airline_icao,flight_number,flight_iataNumber,...,airline_name_yto cargo airlines,departure_iata_khi,departure_iata_lhe,departure_icao_opkc,departure_icao_opla,departure_terminal_h,departure_terminal_i,departure_terminal_m,departure_terminal_main,departure_terminal_t1
3,departure,active,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,2023-07-13 11:30:00,mh,mas,9032,mh9032,...,False,False,True,False,True,False,False,True,False,False
4,departure,active,34.134127,2023-07-13 07:05:00,2023-07-13 07:05:00,2023-07-13 11:30:00,ul,alk,154,ul154,...,False,False,True,False,True,False,False,True,False,False
6,departure,active,34.134127,2023-07-13 08:00:00,2023-07-13 08:00:00,2023-07-13 09:15:00,pk,pia,6453,pk6453,...,False,False,True,False,True,False,False,True,False,False
7,departure,active,10.000000,2023-07-13 09:00:00,2023-07-13 09:00:00,2023-07-13 10:55:00,pa,abq,401,pa401,...,False,False,True,False,True,False,False,True,False,False
8,departure,active,34.134127,2023-07-13 09:25:00,2023-07-13 09:25:00,2023-07-13 11:25:00,ib,ibe,7915,ib7915,...,False,False,True,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7434,departure,active,34.134127,2023-11-01 08:35:00,NaT,2023-11-01 10:45:00,b6,jbu,5586,b65586,...,False,False,True,False,True,False,False,True,False,False
43256,departure,active,18.000000,2024-02-25 13:15:00,2024-02-25 13:25:00,2024-02-25 16:15:00,xy,kne,638,xy638,...,False,True,False,True,False,False,False,True,False,False
32969,departure,active,2.000000,2023-10-17 17:50:00,2023-10-17 17:41:00,2023-10-17 22:00:00,ul,alk,184,ul184,...,False,True,False,True,False,False,False,True,False,False
70669,departure,active,10.000000,2024-02-07 03:10:00,2024-02-07 03:20:00,2024-02-07 05:20:00,wb,rwd,1572,wb1572,...,False,False,False,False,False,False,False,False,False,False
9019,departure,active,40.000000,2023-11-26 03:20:00,2023-11-26 04:00:00,2023-11-26 05:50:00,ac,aca,7617,ac7617,...,False,False,True,False,True,False,False,False,True,False

In [125]:
df_balanced

,type,status,departure_delay,airline_iata,airline_icao,flight_number,flight_iataNumber,flight_icaoNumber,codeshared_airline,codeshared_iata,...,departure_scheduled_month,departure_scheduled_year,departure_estimated_hour,departure_estimated_day,departure_estimated_month,departure_estimated_year,arrival_scheduled_hour,arrival_scheduled_day,arrival_scheduled_month,arrival_scheduled_year
3,departure,active,34.134127,mh,mas,9032,mh9032,mas9032,srilankan airlines,ul,...,7,2023,7.0,13.0,7.0,2023.0,11,13,7,2023
4,departure,active,34.134127,ul,alk,154,ul154,alk154,No Codeshare,NaN,...,7,2023,7.0,13.0,7.0,2023.0,11,13,7,2023
6,departure,active,34.134127,pk,pia,6453,pk6453,pia6453,No Codeshare,NaN,...,7,2023,8.0,13.0,7.0,2023.0,9,13,7,2023
7,departure,active,10.000000,pa,abq,401,pa401,abq401,No Codeshare,NaN,...,7,2023,9.0,13.0,7.0,2023.0,10,13,7,2023
8,departure,active,34.134127,ib,ibe,7915,ib7915,ibe7915,qatar airways,qr,...,7,2023,9.0,13.0,7.0,2023.0,11,13,7,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7434,departure,active,34.134127,b6,jbu,5586,b65586,jbu5586,qatar airways,qr,...,11,2023,NaN,NaN,NaN,NaN,10,1,11,2023
43256,departure,active,18.000000,xy,kne,638,xy638,kne638,No Codeshare,NaN,...,2,2024,13.0,25.0,2.0,2024.0,16,25,2,2024
32969,departure,active,2.000000,ul,alk,184,ul184,alk184,No Codeshare,NaN,...,10,2023,17.0,17.0,10.0,2023.0,22,17,10,2023
70669,departure,active,10.000000,wb,rwd,1572,wb1572,rwd1572,qatar airways,qr,...,2,2024,3.0,7.0,2.0,2024.0,5,7,2,2024
9019,departure,active,40.000000,ac,aca,7617,ac7617,aca7617,emirates,ek,...,11,2023,4.0,26.0,11.0,2023.0,5,26,11,2023

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from scipy.sparse import csr_matrix

def preprocess_and_encode_data(df):
    # Convert timestamp columns to datetime objects if not already
    df['departure_scheduledTime'] = pd.to_datetime(df['departure_scheduledTime'])
    df['departure_estimatedTime'] = pd.to_datetime(df['departure_estimatedTime'])
    df['arrival_scheduledTime'] = pd.to_datetime(df['arrival_scheduledTime'])
    
    # Extract features from datetime columns
    df['departure_scheduled_hour'] = df['departure_scheduledTime'].dt.hour
    df['departure_scheduled_day'] = df['departure_scheduledTime'].dt.day
    df['departure_scheduled_month'] = df['departure_scheduledTime'].dt.month
    df['departure_scheduled_year'] = df['departure_scheduledTime'].dt.year
    
    df['departure_estimated_hour'] = df['departure_estimatedTime'].dt.hour
    df['departure_estimated_day'] = df['departure_estimatedTime'].dt.day
    df['departure_estimated_month'] = df['departure_estimatedTime'].dt.month
    df['departure_estimated_year'] = df['departure_estimatedTime'].dt.year
    
    df['arrival_scheduled_hour'] = df['arrival_scheduledTime'].dt.hour
    df['arrival_scheduled_day'] = df['arrival_scheduledTime'].dt.day
    df['arrival_scheduled_month'] = df['arrival_scheduledTime'].dt.month
    df['arrival_scheduled_year'] = df['arrival_scheduledTime'].dt.year

    # Drop original timestamp columns
    df = df.drop(columns=['departure_scheduledTime', 'departure_estimatedTime', 'arrival_scheduledTime'])
    
    # Define categorical and numerical features
    categorical_features = ['departure_iata', 'departure_icao', 'departure_terminal', 'airline_name']
    numerical_features = ['departure_delay', 'departure_hour', 'departure_day', 'arrival_hour', 'arrival_day',
                          'departure_scheduled_hour', 'departure_scheduled_day', 'departure_scheduled_month',
                          'departure_scheduled_year', 'departure_estimated_hour', 'departure_estimated_day',
                          'departure_estimated_month', 'departure_estimated_year', 'arrival_scheduled_hour',
                          'arrival_scheduled_day', 'arrival_scheduled_month', 'arrival_scheduled_year']
    
    # Apply one-hot encoding to categorical features
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', 'passthrough', numerical_features),
            ('cat', OneHotEncoder(), categorical_features)
        ]
    )
    
    X = preprocessor.fit_transform(df)
    if isinstance(X, csr_matrix):
        X = X.toarray()
    y = df['delay_time_bin'].values  # Assuming delay_time_bin is the target
    
    return X, y

# Preprocess and encode the data
X, y = preprocess_and_encode_data(df_balanced)
print(X.shape)
print(y.shape)

(93604, 122)
(93604,)

In [46]:
import numpy as np

class SVM:
    def __init__(self, kernel='linear', C=1.0):
        self.kernel_name = kernel
        self.C = C
        self.alpha = None
        self.b = 0
        self.X_train = None
        self.y_train = None
        self.n_samples = 0

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        self.n_samples = X.shape[0]
        K = self._compute_kernel_matrix()
        
        # Initialize alpha values
        self.alpha = np.zeros(self.n_samples)
        
        # Optimization process to find alpha (simplified, replace with actual implementation)
        # For debugging, we'll just use a dummy update
        self.alpha = np.random.rand(self.n_samples)
        
        # Calculate bias
        self.b = np.mean(y - np.dot(self.alpha, K.T))
        print(f'Alpha: {self.alpha}')
        print(f'Bias (b): {self.b}')
    
    def _compute_kernel_matrix(self):
        if self.kernel_name == 'linear':
            K = np.dot(self.X_train, self.X_train.T)
        elif self.kernel_name == 'polynomial':
            # Example polynomial kernel, replace with actual polynomial kernel
            K = (np.dot(self.X_train, self.X_train.T) + 1) ** 2
        elif self.kernel_name == 'rbf':
            # Example RBF kernel, replace with actual RBF kernel
            gamma = 0.1
            K = np.exp(-gamma * np.sum((self.X_train[:, np.newaxis] - self.X_train) ** 2, axis=2))
        else:
            raise ValueError("Unsupported kernel")
        
        print(f'Kernel matrix shape: {K.shape}')
        return K

    def _decision_function(self, X):
        K = self._compute_kernel_matrix_for_predict(X)
        print(f'Kernel matrix for decision function shape: {K.shape}')
        
        decision_values = np.dot((self.alpha * self.y_train), K.T) + self.b
        print(f'Decision values shape: {decision_values.shape}')
        return decision_values

    def _compute_kernel_matrix_for_predict(self, X):
        if self.kernel_name == 'linear':
            K = np.dot(X, self.X_train.T)
        elif self.kernel_name == 'polynomial':
            # Example polynomial kernel, replace with actual polynomial kernel
            K = (np.dot(X, self.X_train.T) + 1) ** 2
        elif self.kernel_name == 'rbf':
            # Example RBF kernel, replace with actual RBF kernel
            gamma = 0.1
            K = np.exp(-gamma * np.sum((X[:, np.newaxis] - self.X_train) ** 2, axis=2))
        else:
            raise ValueError("Unsupported kernel")
        
        print(f'Kernel matrix for predict shape: {K.shape}')
        return K

    def predict(self, X):
        decision_values = self._decision_function(X)
        return np.sign(decision_values)

# Example usage with debug prints
if __name__ == "__main__":
    from sklearn.datasets import make_classification

    # Generating dataset with correct parameters
    X, y = make_classification(
        n_samples=100,
        n_features=2,
        n_informative=2,
        n_redundant=0,
        n_repeated=0,
        random_state=42
    )
    
    model = SVM(kernel='linear')
    model.fit(X, y)
    predictions = model.predict(X)
    print(f'Predictions: {predictions}')

Kernel matrix shape: (100, 100)
Alpha: [0.35260035 0.01518578 0.73135007 0.52146898 0.87624438 0.76477462
 0.80837215 0.96326766 0.11334645 0.22743757 0.74682885 0.25700062
 0.81332201 0.39653001 0.49641285 0.95538455 0.07538781 0.73468358
 0.08348436 0.17225161 0.3123429  0.7185369  0.9408897  0.586096
 0.14574158 0.55476489 0.62739576 0.03590247 0.08683068 0.95743059
 0.05016806 0.61053334 0.43455708 0.12021449 0.86769997 0.96884495
 0.77329941 0.21726792 0.55697675 0.34485312 0.05709317 0.05111113
 0.07395709 0.37700632 0.02242246 0.15383402 0.70135647 0.55688257
 0.58639439 0.85160987 0.58558852 0.05005465 0.35114257 0.19778632
 0.32550115 0.33715116 0.15301783 0.50340211 0.40677183 0.08361133
 0.49836233 0.12273928 0.23728122 0.70480756 0.57579962 0.61828594
 0.32651593 0.15843299 0.75149542 0.30297025 0.15940523 0.02294709
 0.73539947 0.76816363 0.52630506 0.77017224 0.16083187 0.66478945
 0.66854252 0.78880487 0.85344826 0.79236036 0.62235573 0.03513934
 0.59424527 0.35935666 0.97481988 0.70330493 0.89563873 0.78900579
 0.31479752 0.95950425 0.78442026 0.91223368 0.97122609 0.49465507
 0.61387286 0.86054246 0.97697241 0.2992442 ]
Bias (b): 0.3000072014763941
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Predictions: [ 1.  1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1.
  1. -1.  1. -1. -1. -1.  1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1.  1.
 -1. -1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1.  1.  1. -1.  1.  1.  1.
 -1. -1. -1.  1. -1. -1. -1.  1.  1.  1. -1.  1. -1. -1. -1.  1.  1. -1.
 -1.  1.  1. -1.  1.  1. -1. -1. -1.  1.  1. -1.  1.  1.  1.  1. -1. -1.
 -1. -1.  1. -1.  1.  1.  1. -1. -1. -1.]

In [49]:
class DecisionTree:
    def __init__(self, max_depth=None):
        self.max_depth = max_depth

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        self.tree = self._build_tree(np.arange(X.shape[0]), 0)
    
    def _build_tree(self, indices, depth):
        """ Recursively build the decision tree """
        if len(set(self.y_train[indices])) == 1:
            return self.y_train[indices][0]
        
        if self.max_depth is not None and depth >= self.max_depth:
            return self._majority_vote(indices)
        
        best_feature, best_threshold = self._best_split(indices)
        if best_feature is None:
            return self._majority_vote(indices)
        
        left_indices = indices[self.X_train[indices, best_feature] <= best_threshold]
        right_indices = indices[self.X_train[indices, best_feature] > best_threshold]
        
        left_tree = self._build_tree(left_indices, depth + 1)
        right_tree = self._build_tree(right_indices, depth + 1)
        
        return (best_feature, best_threshold, left_tree, right_tree)
    
    def _best_split(self, indices):
        """ Find the best feature and threshold to split on """
        best_feature = None
        best_threshold = None
        best_score = -float('inf')
        
        for feature in range(self.X_train.shape[1]):
            thresholds = np.unique(self.X_train[indices, feature])
            for threshold in thresholds:
                left_indices = indices[self.X_train[indices, feature] <= threshold]
                right_indices = indices[self.X_train[indices, feature] > threshold]
                
                if len(left_indices) == 0 or len(right_indices) == 0:
                    continue
                
                score = self._information_gain(indices, left_indices, right_indices)
                if score > best_score:
                    best_feature = feature
                    best_threshold = threshold
                    best_score = score
        
        return best_feature, best_threshold
    
    def _information_gain(self, parent_indices, left_indices, right_indices):
        """ Compute the information gain from a split """
        parent_entropy = self._entropy(parent_indices)
        left_entropy = self._entropy(left_indices)
        right_entropy = self._entropy(right_indices)
        
        p_left = len(left_indices) / len(parent_indices)
        p_right = len(right_indices) / len(parent_indices)
        
        return parent_entropy - (p_left * left_entropy + p_right * right_entropy)
    
    def _entropy(self, indices):
        """ Compute the entropy of a set of indices """
        labels, counts = np.unique(self.y_train[indices], return_counts=True)
        probabilities = counts / len(indices)
        return -np.sum(probabilities * np.log2(probabilities + 1e-10))
    
    def _majority_vote(self, indices):
        """ Return the most common label """
        labels, counts = np.unique(self.y_train[indices], return_counts=True)
        return labels[np.argmax(counts)]
    
    def predict(self, X):
        """ Predict class labels for samples """
        return np.array([self._predict_single(x) for x in X])
    
    def _predict_single(self, x):
        """ Predict the class for a single sample """
        node = self.tree
        while isinstance(node, tuple):
            feature, threshold, left_tree, right_tree = node
            if x[feature] <= threshold:
                node = left_tree
            else:
                node = right_tree
        return node

In [50]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        self.m, self.n = X.shape
        self.theta = np.zeros(self.n)
        self._gradient_descent()

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def _gradient_descent(self):
        for _ in range(self.num_iterations):
            predictions = self._sigmoid(np.dot(self.X_train, self.theta))
            errors = predictions - self.y_train
            gradient = np.dot(self.X_train.T, errors) / self.m
            self.theta -= self.learning_rate * gradient
    
    def predict(self, X):
        probabilities = self._sigmoid(np.dot(X, self.theta))
        return np.where(probabilities >= 0.5, 1, 0)

In [51]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

# Define cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Initialize models
svm_model = SVM(kernel='linear')
dt_model = DecisionTree(max_depth=3)
logistic_model = LogisticRegression()

# Function to perform cross-validation
def cross_validate(model, X, y):
    scores = []
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        scores.append(accuracy)
    return scores

# Evaluate each model
svm_scores = cross_validate(svm_model, X, y)
dt_scores = cross_validate(dt_model, X, y)
logistic_scores = cross_validate(logistic_model, X, y)

print(f'SVM Cross-Validation Scores: {svm_scores}')
print(f'Decision Tree Cross-Validation Scores: {dt_scores}')
print(f'Logistic Regression Cross-Validation Scores: {logistic_scores}')
print(f'SVM Average Accuracy: {np.mean(svm_scores)}')
print(f'Decision Tree Average Accuracy: {np.mean(dt_scores)}')
print(f'Logistic Regression Average Accuracy: {np.mean(logistic_scores)}')

Kernel matrix shape: (80, 80)
Alpha: [0.01022548 0.75742951 0.52638824 0.18980576 0.6258888  0.92217508
 0.72339315 0.63921231 0.73573932 0.97000782 0.18986103 0.26119772
 0.76210815 0.14252882 0.0211281  0.03294387 0.12529467 0.40367426
 0.89428979 0.84801523 0.85743049 0.32845632 0.90057014 0.7247638
 0.39287695 0.09429969 0.37574302 0.07075759 0.10161598 0.86382711
 0.6733297  0.60731312 0.06083627 0.77862044 0.6288798  0.04798687
 0.53069457 0.76422253 0.89141683 0.52387641 0.52467062 0.42529503
 0.81355109 0.30236466 0.42831708 0.59252287 0.89612725 0.60497378
 0.77724779 0.8874452  0.1698236  0.91670129 0.38751537 0.21702225
 0.00874195 0.75596702 0.48544706 0.23697548 0.03525398 0.81580853
 0.94125266 0.77045604 0.53208215 0.00184703 0.65467581 0.53529102
 0.65562716 0.79372255 0.91588354 0.0394536  0.3870135  0.4951203
 0.71459178 0.36107194 0.16784248 0.27782153 0.27780446 0.87712709
 0.66488832 0.63701521]
Bias (b): 0.44254080256309225
Kernel matrix for predict shape: (20, 80)
Kernel matrix for decision function shape: (20, 80)
Decision values shape: (20,)
Kernel matrix shape: (80, 80)
Alpha: [0.78486429 0.31467318 0.75425807 0.71728707 0.64674677 0.42533804
 0.23782497 0.52938123 0.57462792 0.05817173 0.9924563  0.20212728
 0.25189213 0.96584936 0.86026211 0.03953119 0.56700539 0.40850934
 0.90959726 0.09112384 0.06120627 0.56207911 0.04109191 0.37214262
 0.39555908 0.93161173 0.63114764 0.01550264 0.02365263 0.77143385
 0.51241835 0.68191549 0.73778227 0.90086316 0.33203862 0.49879153
 0.21963664 0.26612354 0.73193657 0.66915745 0.06983133 0.43104952
 0.46210878 0.16457081 0.03595613 0.25475774 0.87255139 0.27300532
 0.01166906 0.09613503 0.41707857 0.53490334 0.55818269 0.45950534
 0.4239372  0.18102973 0.33160626 0.4911401  0.07450127 0.00286874
 0.4748391  0.38961138 0.02755423 0.91843911 0.56307406 0.76398292
 0.69812456 0.90109929 0.3983531  0.95212353 0.4376555  0.45098851
 0.50726929 0.82921167 0.16690883 0.42360287 0.09699149 0.23721865
 0.88893122 0.84962928]
Bias (b): 0.22762056123420135
Kernel matrix for predict shape: (20, 80)
Kernel matrix for decision function shape: (20, 80)
Decision values shape: (20,)
Kernel matrix shape: (80, 80)
Alpha: [0.31084617 0.66824634 0.14993637 0.18963069 0.46779646 0.60308493
 0.95660826 0.3691689  0.03751934 0.61968696 0.25265053 0.76364811
 0.13978962 0.31773265 0.40038239 0.1888436  0.10037284 0.93173469
 0.41114973 0.48426623 0.04798077 0.07041115 0.72425697 0.9713993
 0.12992344 0.87809445 0.82811592 0.76186455 0.36847543 0.22290049
 0.13792624 0.48373341 0.52656563 0.21272565 0.82821634 0.42919281
 0.40506656 0.87675964 0.36523806 0.32755033 0.38287781 0.23514862
 0.60409449 0.29726003 0.42212552 0.81974931 0.24438111 0.66593919
 0.05331048 0.98954312 0.8290083  0.40048623 0.70967445 0.17798138
 0.52263893 0.91024959 0.92245173 0.83470743 0.17336233 0.17225587
 0.56417955 0.3882742  0.79725087 0.59017294 0.49562981 0.8228056
 0.92615414 0.89966835 0.13417826 0.20970016 0.8345388  0.40450492
 0.99770076 0.55230289 0.96612468 0.57367889 0.76386148 0.86490795
 0.41951459 0.59863292]
Bias (b): 0.4903207097377863
Kernel matrix for predict shape: (20, 80)
Kernel matrix for decision function shape: (20, 80)
Decision values shape: (20,)
Kernel matrix shape: (80, 80)
Alpha: [5.23829409e-01 6.33984311e-01 2.32077485e-01 8.16382766e-01
 9.73079789e-01 6.77394948e-01 2.42340908e-01 7.85978734e-01
 9.54490325e-01 4.53364322e-01 6.76848937e-01 8.10569898e-01
 3.82550897e-01 7.15324950e-01 8.00217142e-01 6.36022745e-01
 1.07496738e-02 5.06043604e-01 5.83726020e-01 3.65763750e-01
 2.41418942e-01 3.92733926e-01 7.72106888e-01 4.18129302e-01
 7.52268080e-01 2.90154821e-01 4.42537506e-01 3.74026467e-01
 4.39977148e-01 5.73330173e-01 4.50328777e-01 7.38984451e-02
 7.41382305e-01 2.29129703e-01 2.67170340e-01 5.22080645e-01
 4.15443267e-01 8.50611568e-01 5.82002131e-01 8.98646504e-01
 1.55840649e-01 8.30580230e-01 2.35358352e-01 2.71040826e-01
 6.88704854e-01 5.46752588e-02 1.07122017e-01 3.40219359e-02
 8.48869563e-01 4.83496722e-01 7.22852392e-02 5.35744492e-01
 7.00869281e-01 8.96586615e-01 2.61295407e-01 9.92393492e-02
 8.18288190e-01 1.86913792e-01 3.58192822e-01 7.14989901e-01
 2.76820604e-01 7.07305371e-01 7.40765502e-01 9.12274599e-01
 9.54008588e-01 6.15517179e-01 7.90195306e-01 2.49807841e-01
 2.90972172e-01 8.14715055e-04 2.29713283e-01 1.57013177e-01
 9.75601618e-01 3.74274028e-01 1.30425419e-01 5.00311666e-02
 6.49849442e-01 1.15754504e-01 4.99758289e-01 1.97939855e-01]
Bias (b): -0.2547814473406357
Kernel matrix for predict shape: (20, 80)
Kernel matrix for decision function shape: (20, 80)
Decision values shape: (20,)
Kernel matrix shape: (80, 80)
Alpha: [0.03266406 0.10512282 0.12804174 0.80970058 0.57297744 0.6408724
 0.29320576 0.09560168 0.63131026 0.01341709 0.57814029 0.62679934
 0.61555266 0.57323286 0.51290328 0.54585044 0.46640409 0.01339843
 0.58917338 0.47932289 0.74798352 0.97978633 0.57873275 0.6042242
 0.12974399 0.75123428 0.18527069 0.56277588 0.60542649 0.45664781
 0.8139759  0.5758213  0.07225563 0.41875344 0.85066292 0.1045672
 0.70987931 0.71398112 0.17259894 0.20753696 0.5911115  0.42394587
 0.62157669 0.97768484 0.15602672 0.55455076 0.71215597 0.92422654
 0.36730116 0.44560199 0.16801344 0.78277231 0.11031631 0.76325659
 0.90424199 0.48261069 0.26639671 0.90519994 0.42925365 0.48200795
 0.1876066  0.57971811 0.3646913  0.71613481 0.0593804  0.95566103
 0.6426874  0.37971818 0.38735433 0.14030578 0.32081982 0.98640229
 0.09058253 0.63951445 0.77066199 0.80111389 0.28199538 0.43611362
 0.58731724 0.84131347]
Bias (b): 0.23589954391027934
Kernel matrix for predict shape: (20, 80)
Kernel matrix for decision function shape: (20, 80)
Decision values shape: (20,)
SVM Cross-Validation Scores: [0.45, 0.45, 0.45, 0.35, 0.6]
Decision Tree Cross-Validation Scores: [0.95, 0.95, 1.0, 1.0, 0.9]
Logistic Regression Cross-Validation Scores: [0.95, 0.95, 1.0, 1.0, 0.95]
SVM Average Accuracy: 0.4600000000000001
Decision Tree Average Accuracy: 0.96
Logistic Regression Average Accuracy: 0.97

In [58]:
class Bagging:
    def __init__(self, base_model_class, n_estimators=10, **base_model_kwargs):
        self.base_model_class = base_model_class
        self.n_estimators = n_estimators
        self.base_model_kwargs = base_model_kwargs
        self.models = []

    def fit(self, X, y):
        self.models = []
        for _ in range(self.n_estimators):
            # Bootstrap sampling
            indices = np.random.choice(len(X), len(X), replace=True)
            X_bootstrap, y_bootstrap = X[indices], y[indices]
            
            model = self.base_model_class(**self.base_model_kwargs)
            model.fit(X_bootstrap, y_bootstrap)
            self.models.append(model)
    
    def predict(self, X):
        # Collect predictions from each model
        predictions = np.zeros((X.shape[0], self.n_estimators))
        for i, model in enumerate(self.models):
            predictions[:, i] = model.predict(X)
        
        # Perform majority voting
        # Convert predictions to integers (assuming binary classification: -1 or 1)
        majority_votes = np.array([np.bincount(row.astype(int) + 1).argmax() - 1 for row in predictions])
        return majority_votes

In [59]:
# Create Bagging models for each base model with appropriate parameters
bagging_svm = Bagging(base_model_class=SVM, n_estimators=10, kernel='linear')
bagging_dt = Bagging(base_model_class=DecisionTree, n_estimators=10, max_depth=3)
bagging_logistic = Bagging(base_model_class=LogisticRegression, n_estimators=10, learning_rate=0.01, num_iterations=1000)

# Fit each model
bagging_svm.fit(X, y)
bagging_dt.fit(X, y)
bagging_logistic.fit(X, y)

# Collect predictions from each model
svm_predictions = bagging_svm.predict(X)
dt_predictions = bagging_dt.predict(X)
logistic_predictions = bagging_logistic.predict(X)

# Stack predictions for majority voting
stacked_predictions = np.stack([svm_predictions, dt_predictions, logistic_predictions], axis=1)

# Perform majority voting
final_predictions = np.array([np.bincount(row.astype(int) + 1).argmax() - 1 for row in stacked_predictions])

# Calculate accuracy
final_accuracy = accuracy_score(y, final_predictions)
print(f'Final Accuracy with Bagging and Majority Voting: {final_accuracy}')

Kernel matrix shape: (100, 100)
Alpha: [0.23110147 0.92053329 0.91049259 0.58881542 0.16948962 0.59904341
 0.76125204 0.2108592  0.75242241 0.46175828 0.06044441 0.87935118
 0.36305797 0.25244012 0.71760134 0.69250077 0.50768912 0.07194543
 0.1732385  0.88080528 0.1686562  0.16200556 0.45206397 0.35155065
 0.45484116 0.36776702 0.5044781  0.67681274 0.91748797 0.02310565
 0.87714401 0.35530799 0.9546889  0.79779477 0.75710936 0.47681019
 0.87370677 0.22625249 0.76961708 0.6872328  0.6307632  0.14629853
 0.11156968 0.29663087 0.22912714 0.65443202 0.32373906 0.05699055
 0.92614455 0.88031972 0.51266952 0.37704174 0.52604625 0.72767372
 0.28616768 0.64599995 0.69038758 0.80427977 0.77621602 0.06897441
 0.17331294 0.30467238 0.06808912 0.15748431 0.09458673 0.77054457
 0.85721475 0.89817876 0.80430915 0.95985607 0.50956154 0.67522544
 0.53797285 0.25530781 0.18686925 0.10236191 0.41698218 0.77878324
 0.44232586 0.29310048 0.02839463 0.13897989 0.44738106 0.42721459
 0.92533242 0.75542127 0.42753649 0.80878089 0.19391211 0.70584867
 0.1667766  0.50682755 0.68334427 0.91390083 0.05461101 0.21559313
 0.72746408 0.52219882 0.72390843 0.20216017]
Bias (b): -0.14562206401088992
Kernel matrix shape: (100, 100)
Alpha: [0.77673373 0.66343079 0.47121488 0.63111369 0.44580158 0.71790454
 0.87586652 0.3189528  0.95865922 0.23539312 0.04764247 0.8827517
 0.01675462 0.6405022  0.71942299 0.97238662 0.18494346 0.54120013
 0.25432303 0.64875651 0.94343938 0.87959606 0.46383629 0.81681277
 0.77325348 0.80276428 0.58896138 0.04002266 0.76673205 0.87757975
 0.87331997 0.65276207 0.01646727 0.01544118 0.8932631  0.32979739
 0.40185088 0.97646302 0.09275427 0.17060121 0.97732629 0.59922988
 0.16671459 0.13545319 0.09836017 0.19172901 0.01400186 0.66038786
 0.32211695 0.89961296 0.22072665 0.52283961 0.27516755 0.91780846
 0.26084449 0.08433424 0.33571347 0.80902566 0.69966366 0.57761308
 0.69113543 0.85141509 0.03902117 0.43512867 0.45347311 0.78361092
 0.06201929 0.08530296 0.10012083 0.70397699 0.75611255 0.83618105
 0.26862261 0.94117442 0.71080408 0.80796603 0.23797697 0.32604755
 0.65382456 0.34390056 0.96954314 0.13357367 0.77424534 0.2317434
 0.08318601 0.36007384 0.06152402 0.95036592 0.89879967 0.1904991
 0.20741873 0.13896606 0.90733786 0.05557373 0.15926114 0.71541248
 0.06202076 0.21516744 0.21359298 0.23467475]
Bias (b): -0.8216547064719393
Kernel matrix shape: (100, 100)
Alpha: [0.27663258 0.95162026 0.5471139  0.53315925 0.04026813 0.79598528
 0.42155179 0.42633964 0.20918596 0.38231834 0.52163875 0.94098142
 0.25575125 0.11775609 0.57736603 0.54749449 0.08692621 0.18901329
 0.24053487 0.08186881 0.32174449 0.54637669 0.70865052 0.21658567
 0.64459818 0.32966839 0.34361704 0.76645823 0.80716517 0.77667062
 0.73635619 0.33690578 0.39021503 0.90370909 0.54120819 0.43741055
 0.01306482 0.73179956 0.61620154 0.85033853 0.49047367 0.18732275
 0.19405176 0.76227526 0.20965499 0.83573713 0.93488704 0.32596777
 0.09317224 0.3447172  0.05925283 0.4330542  0.11072966 0.89308887
 0.92669922 0.38366593 0.8886136  0.94160797 0.45208415 0.81605359
 0.59672479 0.87983202 0.66797592 0.55279653 0.96759371 0.29775377
 0.4363633  0.67570988 0.87815138 0.53901365 0.83968224 0.87353299
 0.7765879  0.12003306 0.66666747 0.47600814 0.74806525 0.51304112
 0.22797811 0.73590035 0.8530628  0.09386173 0.46120533 0.9800794
 0.04934042 0.64345929 0.57616048 0.52652376 0.83561023 0.55129128
 0.12076223 0.25283608 0.12249472 0.2755813  0.23970071 0.62402765
 0.47891404 0.02708832 0.16880393 0.37431989]
Bias (b): 0.07106821084207211
Kernel matrix shape: (100, 100)
Alpha: [0.40510352 0.2887305  0.06352985 0.15285845 0.18820923 0.66948476
 0.30026256 0.4199967  0.43219991 0.03841532 0.85466733 0.81881869
 0.07218857 0.03905077 0.80611234 0.91881571 0.23032596 0.61361345
 0.1163379  0.83606542 0.97895977 0.28891441 0.69001506 0.39297127
 0.70874763 0.05761375 0.42506026 0.18392398 0.3060184  0.76247976
 0.37603097 0.5671482  0.12381128 0.52116619 0.6853235  0.44669093
 0.62999872 0.37215664 0.40361039 0.98214229 0.53309605 0.87386703
 0.60073597 0.34415972 0.2660671  0.60301035 0.41414763 0.02108347
 0.50335762 0.0792978  0.00894128 0.27962163 0.64816142 0.45474582
 0.44508607 0.37635529 0.14244081 0.98589008 0.00153718 0.3253252
 0.65904562 0.59910265 0.0592131  0.35052431 0.65310462 0.42335953
 0.72826394 0.67334124 0.07279713 0.60494276 0.44165924 0.40892367
 0.78351298 0.45035225 0.38223062 0.38120299 0.30606487 0.14921819
 0.64477738 0.10580429 0.43424487 0.89161561 0.74918077 0.27196854
 0.62749328 0.17106499 0.22617016 0.70007677 0.59310574 0.7825043
 0.44805729 0.74629292 0.86241118 0.7123069  0.77763723 0.39135612
 0.61776975 0.67923515 0.43598859 0.22916529]
Bias (b): -5.702900435517746
Kernel matrix shape: (100, 100)
Alpha: [0.46742473 0.26949996 0.50859123 0.92344287 0.62166974 0.2979698
 0.61934714 0.27651864 0.32814473 0.33251482 0.1289963  0.12564996
 0.73417583 0.90701751 0.41927872 0.06039812 0.71129768 0.0839883
 0.07825454 0.46679391 0.36191474 0.82071557 0.20355846 0.29493374
 0.52359911 0.67636881 0.34793075 0.40370188 0.05636721 0.19302613
 0.41070782 0.88325368 0.04791536 0.95548515 0.14353288 0.80526569
 0.58428659 0.34321662 0.19867269 0.14884946 0.26531874 0.21649368
 0.92233695 0.25522884 0.89012768 0.50307988 0.29069258 0.67460848
 0.25772552 0.40940884 0.73854519 0.38879344 0.28000236 0.67330208
 0.78609754 0.75443802 0.82430136 0.06098729 0.34994984 0.4722845
 0.06244686 0.06916406 0.93579215 0.52474901 0.35646205 0.87945217
 0.64291008 0.56899545 0.06472937 0.30887822 0.87539823 0.17980222
 0.6028121  0.68093146 0.96231768 0.65819602 0.47536438 0.74700517
 0.32362153 0.68143507 0.46010506 0.86045028 0.20079502 0.23818308
 0.31756625 0.13350202 0.6134227  0.14759634 0.59627779 0.40678878
 0.72626835 0.6400651  0.66561625 0.76465311 0.45738812 0.2661979
 0.25756192 0.98053969 0.26091204 0.55557758]
Bias (b): 0.4156635205902582
Kernel matrix shape: (100, 100)
Alpha: [0.1694969  0.0389165  0.11489346 0.60181511 0.66174673 0.67468498
 0.95159704 0.60828613 0.37829294 0.35496135 0.26450668 0.82706127
 0.83952485 0.83353635 0.80318978 0.17141248 0.16926613 0.53191164
 0.80866238 0.31768045 0.30859765 0.23742228 0.27393347 0.94429559
 0.42333904 0.69735985 0.901713   0.50996938 0.62422591 0.98549561
 0.77670664 0.81089059 0.30663226 0.11855381 0.15091613 0.79010014
 0.20707667 0.23576697 0.5656645  0.45213528 0.08340616 0.79214075
 0.48023492 0.96477036 0.13739459 0.65062236 0.54446847 0.69499645
 0.23488317 0.85575228 0.3103389  0.82113242 0.27824543 0.53350797
 0.74512438 0.34470993 0.79833674 0.28377262 0.03800219 0.74515546
 0.38918237 0.26650979 0.41063042 0.84909306 0.18790128 0.44812983
 0.34956841 0.25128069 0.74210923 0.29995933 0.26865494 0.10476203
 0.00155489 0.56039725 0.74394678 0.99539902 0.79434964 0.52196921
 0.68666671 0.48603789 0.84887603 0.88190209 0.63218411 0.166135
 0.61628427 0.16188399 0.42798538 0.26315399 0.9143243  0.13969255
 0.25321809 0.15723055 0.95676208 0.28511488 0.80379231 0.63616502
 0.68998049 0.54932565 0.54174806 0.06771974]
Bias (b): -3.155507510065466
Kernel matrix shape: (100, 100)
Alpha: [0.74070669 0.55181744 0.39168563 0.06608985 0.07837081 0.9046966
 0.94241085 0.41716652 0.50664171 0.06490508 0.84558408 0.25005967
 0.58575819 0.67069459 0.62814112 0.28478371 0.78928124 0.89299992
 0.87804693 0.08244768 0.5590288  0.50147209 0.76677375 0.84154631
 0.85245385 0.41755401 0.10816416 0.43480881 0.19203417 0.54172749
 0.85204041 0.79377622 0.35713196 0.68612426 0.28614881 0.54844166
 0.61590529 0.69919    0.05661966 0.77008305 0.55158911 0.41279308
 0.4031927  0.81518685 0.1640747  0.90256405 0.59271696 0.92518738
 0.68884731 0.78471501 0.54161181 0.61548359 0.72836357 0.30834392
 0.60288923 0.05616287 0.19508082 0.90387553 0.82162244 0.68045729
 0.72532348 0.76683144 0.74226179 0.25593924 0.31486311 0.67032553
 0.45563438 0.81696133 0.58346932 0.65009132 0.61916001 0.54512978
 0.21248988 0.21097787 0.14123501 0.90475434 0.91007689 0.02556213
 0.01641    0.43713919 0.98934817 0.55270524 0.65670719 0.41444764
 0.16834007 0.39339662 0.60749683 0.26208709 0.78469723 0.20570975
 0.7718329  0.54824993 0.61495903 0.32721264 0.17381625 0.69887813
 0.11230781 0.43541582 0.67744846 0.88396768]
Bias (b): -1.2312577264877078
Kernel matrix shape: (100, 100)
Alpha: [0.21486027 0.1787263  0.25695545 0.32391618 0.23228846 0.21370042
 0.14451132 0.46404493 0.76614189 0.66919058 0.03352131 0.27798448
 0.74270318 0.8067075  0.15779368 0.03001386 0.79066328 0.96033719
 0.09908105 0.7133373  0.88731159 0.90277793 0.26241011 0.13117101
 0.03065848 0.54344278 0.25609338 0.33782667 0.05119605 0.49516938
 0.19895987 0.92804932 0.80893129 0.44234566 0.9241935  0.69113941
 0.20346663 0.2325583  0.44450112 0.07540936 0.7848944  0.73174294
 0.69677552 0.01181987 0.65344682 0.84391474 0.08360526 0.67468417
 0.94713874 0.73876101 0.82204572 0.81450221 0.41980597 0.85865047
 0.95541077 0.09259426 0.14786632 0.51430033 0.65303311 0.99902184
 0.91829038 0.69880697 0.40363103 0.02382425 0.94091726 0.64916963
 0.39897252 0.40997367 0.26774627 0.21769998 0.42057551 0.15992213
 0.44337315 0.67677386 0.22490539 0.39625588 0.13629638 0.08806325
 0.53799222 0.80430937 0.90289684 0.21103991 0.37855565 0.48195401
 0.66812075 0.2576753  0.65824257 0.12263451 0.48365408 0.14803024
 0.65800994 0.38096072 0.55271235 0.47848331 0.49230266 0.6730822
 0.65873905 0.46885594 0.59638308 0.40231685]
Bias (b): -0.1215675782791557
Kernel matrix shape: (100, 100)
Alpha: [0.20253373 0.65966681 0.61175639 0.44430074 0.56051552 0.20923755
 0.50635794 0.27599774 0.6880519  0.6144963  0.75388985 0.62566816
 0.09817674 0.76061885 0.92810134 0.45090681 0.4556694  0.83147661
 0.90391807 0.54276151 0.69308939 0.98347035 0.46218081 0.50225022
 0.29046846 0.15386515 0.91794885 0.54680691 0.19922015 0.17845517
 0.84741968 0.77944349 0.91577384 0.03131941 0.49998971 0.76191788
 0.95179266 0.924599   0.58065258 0.2345923  0.45123814 0.53589176
 0.78469955 0.37884994 0.40928398 0.59043526 0.95729778 0.08616798
 0.12671993 0.84440179 0.59581723 0.82992938 0.4436254  0.78486277
 0.25937458 0.61347052 0.02368962 0.88896643 0.29077992 0.48137793
 0.77953302 0.76258954 0.47434401 0.84697699 0.41199564 0.75843232
 0.10178474 0.33063588 0.21670327 0.78527436 0.28401955 0.32614885
 0.19507093 0.76761081 0.20936283 0.56815616 0.47317743 0.6809782
 0.54438535 0.77552981 0.66387804 0.01129209 0.24059544 0.26261935
 0.16752179 0.77769104 0.66894978 0.0936749  0.32537889 0.76689578
 0.92235326 0.98847038 0.59797687 0.50312431 0.49366286 0.96986837
 0.33837284 0.50458141 0.00926063 0.88220389]
Bias (b): 0.16039710364821766
Kernel matrix shape: (100, 100)
Alpha: [0.38707779 0.01281388 0.10794602 0.73632572 0.27197856 0.04943593
 0.95768426 0.55824981 0.58811373 0.92609843 0.43939249 0.24441511
 0.77856499 0.47066031 0.92376596 0.57559178 0.15212694 0.06291067
 0.04161938 0.03395118 0.813787   0.14011361 0.09222792 0.56696878
 0.40167979 0.00151863 0.39497426 0.38410032 0.4266798  0.65462505
 0.29021069 0.73671465 0.99892277 0.3875749  0.24890812 0.38729357
 0.26121821 0.59882742 0.19156491 0.70247501 0.37644521 0.12543084
 0.06554678 0.85515746 0.53552117 0.10766691 0.65618062 0.52436672
 0.79939401 0.7784697  0.30804723 0.62754448 0.38596521 0.0971948
 0.99831959 0.51331841 0.80829644 0.649901   0.691998   0.96581861
 0.47954742 0.79531946 0.75017478 0.84465634 0.30246093 0.06879355
 0.44579554 0.2073704  0.08020121 0.65428408 0.62496293 0.53351386
 0.57561818 0.4491666  0.39217912 0.16225881 0.80381511 0.09251306
 0.11664679 0.94673523 0.70073649 0.59578459 0.95466173 0.33605606
 0.38305493 0.07482732 0.26428269 0.28170268 0.5612234  0.09120032
 0.09112277 0.12760325 0.13113867 0.2474327  0.771541   0.85598633
 0.25084329 0.12554255 0.60728508 0.38245469]
Bias (b): -1.0723016635524842
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Kernel matrix for predict shape: (100, 100)
Kernel matrix for decision function shape: (100, 100)
Decision values shape: (100,)
Final Accuracy with Bagging and Majority Voting: 0.98